#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d91pu0rtqb8s739gh0tg-a.singapore-postgres.render.com/moneymanager_ilya
spring.datasource.username=moneymanager_ilya_user
spring.datasource.password=8Yu1vioIZpi1528bW5QyEZA2LRlEXzno